/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface KsCalc {

    /**
     * 入力する文字列
     */
    input?:string

    /**
     * 計算結果
     */
    output?:number

  }
  interface KsCalcAttributes extends StencilHTMLAttributes {
    /**
     * 入力する文字列
     */
    input?:string

    /**
     * 計算結果
     */
    output?:number
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'KsCalc': Components.KsCalc;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'ks-calc': Components.KsCalcAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLKsCalcElement extends Components.KsCalc, HTMLStencilElement {}
  var HTMLKsCalcElement: {
    prototype: HTMLKsCalcElement;
    new (): HTMLKsCalcElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'ks-calc': HTMLKsCalcElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'ks-calc': HTMLKsCalcElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
